### ISSUE TITLE
Thoughts and roadblocks for evolving this framework

### ISSUE THREAD

**Issue by drewburlingame** [bilal-fazlani/commanddotnet#149]
Hi @bilal-fazlani and other users of this framework.  I've had some time to put into this framework lately and I've been enjoying diving into it.   

I've recently been working toward introducing a middleware framework to soon be followed by additional features like rsp files, injecting piped input, making remaining arguments work and making some behaviors more consistent.

While working on this, I've been cautious of introducing breaking changes.  In the next round of changes I had planned, there will be some breaking changes for more advanced scenarios like custom help providers, custom invokers, argument transformations.  You can see some of those here.  My plan was to have two stages of changes.  Stage 1 would be backward compatible with warnings that would direct you on how to update any customizations you have.  Stage 2 would remove the obsolete code and be marked as a breaking change release.  You can see this in these 2 PRs. https://github.com/bilal-fazlani/commanddotnet/pull/146  &  https://github.com/bilal-fazlani/commanddotnet/pull/148

I made good progress but as I try to untangle ArgumentInfo, I'm not seeing simple ways to follow the pattern I've been following.   The next set of changes will see a lot of churn with ArgumentInfo and usages.  I'll be creating more clear breaks general command execution logic vs logic mapping commands & arguments to code constructs.    The breaking changes will still primarily impact advanced use cases.  If you haven't written any custom code behavior will remain generally consistent.  Your app will compile and run as it does.

I'd like to check in with the @bilal-fazlani  and the group to see what your desire & tolerance is for these types of changes.  Are people using the custom logic?  Will it be worth the changes to see the new features introduced?  Should I spin these changes off into a new project?  If there's enough interest I'd like to keep working within an existing community instead of creating a new one.

@bilal-fazlani what are your thoughts?

**Comment by bilal-fazlani** [comment]
I, personally, have never really been bothered about backward compatibility.

If a change improves the project but requires changes in APIs, IMO, we should make that change because otherwise we are holding back on all the good things a library or framework could have provided. 

Upgrading is always a choice.

My only obsession is ease of use. Basic features should be very intuitive and predictable. For advanced features, we should try that they as as intuitive as possible and ensure that they do not affect the "ease of use" factor of basic features and the overall framework. I think so far, we have done a good job at this. 

It will be good if this existing codebase evolves with the things that you are planning @Drew. But it's open source! So you can always fork and spin up something new if you feel the objectives are not in alignment.

**Comment by drewburlingame** [comment]
Sounds like we're still aligned.  I'll focus more on the changes and spend less time on backward compatibility.  I agree on remaining as intuitive as possible.  I plan to follow existing patterns where additional configuration is required, like registering middleware components.  And I think the clearer boundaries in code along with some documentation will make it easier for devs to understand where logic lives and why and make contributing easier. 

Thanks for responding @bilal-fazlani .
