### ISSUE TITLE
How are duplicated parameters being handled?

### ISSUE THREAD

**Issue by taori** [bilal-fazlani/commanddotnet#188]
dotnet build can be called like `dotnet build /p:IncludeSymbols=True /p:PackAsTool=True` or `dotnet build /p:IncludeSymbols=True;PackAsTool=True` I did not find anything about this in the docs. Is that usage scenario covered?

@drewburlingame  Since you're busy with docs atm, i figured you might be aware of it if that were the case.

**Comment by drewburlingame** [comment]
Hi @taori, thanks for the questions.  

When possible, if I can answer them by updating docs, I would like to do that to help drive the documentation I'm working on.  To that end, I've added a doc for Token Transformation, but Travis doesn't seem to be running builds atm.  Perhaps they'll have run and deployed the updated docs by the time you read this.  Look under Extensiblity \ Token Transformations

CommandDotNet does not support the syntax you've posted.  It doesn't support the `/p:` or splitting on `;`

I think it would be simple enough to support by creating a TokenTransformation.  You can see examples in the ___Transformation.cs classes found [here](https://github.com/bilal-fazlani/commanddotnet/tree/beta-v3/master/CommandDotNet/Tokens) 

There would be two steps.
1) inspect all Value type tokens.  If they start with `/p`, convert them to Option token, trimming away the `/p` for the value.  
2) split on `;`, creating a new Option token per part.  Splitting could be a separate transformation.

The framework will already split on assignment so you won't need to handle that here.

I don't plan to add support for those personally, but if you'd like to submit a PR with tests, I'll review it since this seems to be a MS pattern. Or you could create a nuget package and we can create a help page to reference 3rd party packages.

**Comment by drewburlingame** [comment]
https://bilal-fazlani.github.io/commanddotnet/V3/Extensibility/token-transformations/

**Comment by taori** [comment]
That sounds great. Thanks for your answer.
