### ISSUE TITLE
Brackets do not group strings which contain spaces and are chunked instead

### ISSUE THREAD

**Issue by taori** [bilal-fazlani/commanddotnet#59]
Great project!

I've had one issue though. For a program i wrote i had a string which contained bracket, which raised a unrecognized parameter exception. something like :

application command "some (text)"

using a signature like

void Command(string name)

Is this a bug, or is it just incorrect/unexpected syntax?

**Comment by bilal-fazlani** [comment]
I will try to reprpduce this

**Comment by taori** [comment]
@bilal-fazlani thanks. You can use the following code to reproduce it:


    public class StringValueParserTests : TestBase
    {
        [Theory]
        [InlineData("test config sometext", 0)]
        [InlineData("test config \"sometext (and more)\"", 0)]
        public void TestValues(string input, int expectedCode)
        {
            var app = new AppRunner<StringValueApplication>(new AppSettings(){Case = Case.LowerCase});
            var result = app.Run(input.Split(' '));
            result.Should().Be(expectedCode);
        }

        private class StringValueApplication
        {
            public int Test(
                [Argument(Name = "action")]
                string actionType,
                string text)
            {
                return 0;
            }
        }

        /// <inheritdoc />
        public StringValueParserTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }
    }

**Comment by bilal-fazlani** [comment]
Alright I looked into it. 

I simplified the app. and it looks like this:

```c#
class Issue55
{
    public void process(string key)
    {
        Console.WriteLine(key);
    }
}
```
and this test fails:

```c#
[Fact]
public void ShouldAcceptBracketAsInputParameter()
{
    var app = new AppRunner<Issue55>(new AppSettings(){Case = Case.LowerCase});
    var result = app.Run("process \"sometext (and more)\"".Split(' '));
    result.Should().Be(0);
}
```

let's look at what's happening- Since this is a tests and we don't have handle to the actual main method, we have use string.split to split our full command by spaces. To combine the argument `sometext (and more)` into one argument we used `"` double quotes.

The split by spaces doesn't create proper result though. It creates this array : 
["process", "\"sometext", "(and", "more)\"]

Clearly this is not what we were expecting. We want ["process", "sometext (and more)"] for it to function properly

When I run this test it works: 

```c#
[Fact]
public void ShouldAcceptBracketAsInputParameter2()
{
    var app = new AppRunner<Issue55>(new AppSettings(){Case = Case.LowerCase});
    var result = app.Run("process" ,"sometext (and more)");
    result.Should().Be(0);
}
```

I tested it from command line also (on a mac) : 

<img width="1440" alt="screenshot 2019-01-02 at 9 26 52 pm" src="https://user-images.githubusercontent.com/3396271/50599810-1da9c900-0ed5-11e9-9006-e3a8147fd2e5.png">

It worked fine for me with double quotes. Has this failed for you from CLI ?

**Comment by taori** [comment]
Thanks for verifying - yeah - it failed from cli. so it appears that the arguments are parsed like in the first case and have to be rebuilt before being processed further. I'll see if i can provide a PR for you to spare you some work which suceeds all tests. Gotta pay back some gratitude for all the work that has been put into your project :)

**Comment by taori** [comment]
internal class ArgumentParser
    {
        private static readonly Regex ArgumentsSplitRegex = new Regex(@"(?<!\\)"".+(?<!\\)""|(?<!\\)'.+(?<!\\)'|[^\s]+", RegexOptions.Compiled);

        public static IEnumerable<string> SplitFlags(params string[] args)
        {
            var joined = string.Join(" ", args);
            foreach (Match match in ArgumentsSplitRegex.Matches(joined))
            {
                yield return match.Value;
            }
        }
    }

Changing the argument parser to this fixes the issue, but causes a couple other errors though. gonna check if those are expected errors or edge cases where the syntax would not be compatible.

**Comment by taori** [comment]
according to the code samples at https://chris.beams.io/posts/git-commit/ using `"` or `'` to group a string as argument, seems to be an established pattern, so it's actually the unit tests, which have the invalid syntax (if this PR were to be merged), instead of the regex behaving unexpected. Do you agree?

**Comment by taori** [comment]
There is an issue with parameter combinations like -ab being equivalent to -a -b 

Is this standard console behavior? I can't remember having seen such a syntax before, since that would also require additional validation whether a command which has -a and -b does not also have -ab.

**Comment by taori** [comment]
https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/
> Recall2 that the CommandLineToArgV convention3 stipulates that arguments containing spaces be surrounded by double quotation marks. Following the above approach and surrounding arguments with quotation marks produces good results for simple cases, and many people stop here. 

Looks like quotation marks are a common convention then

**Comment by taori** [comment]
@bilal-fazlani something not ok with the PR?

**Comment by bilal-fazlani** [comment]
I need some time to go throug it. (Couple of days)

**Comment by bilal-fazlani** [comment]
@taori 

>There is an issue with parameter combinations like -ab being equivalent to -a -b
>Is this standard console behavior? I can't remember having seen such a syntax before, since that >would also require additional validation whether a command which has -a and -b does not also have -ab.

https://serverfault.com/questions/387935/whats-the-difference-betwen-the-single-dash-and-double-dash-flags-on-shell-comm

I have seen that many command line apps follow this convention

**Comment by taori** [comment]
> 
> 
> @taori right now, systax like this is also supported:
> 
> ```cs
> dotnet example.dll --key=value
> ```
> 
> is that still supported in the PR?

that results in ["dotnet", "example.dll", "--key=value"]. If there was no test for that, there is one now in the PR - so yeah. should be working

**Comment by taori** [comment]
> 
> 
> @taori
> 
> > There is an issue with parameter combinations like -ab being equivalent to -a -b
> > Is this standard console behavior? I can't remember having seen such a syntax before, since that >would also require additional validation whether a command which has -a and -b does not also have -ab.
> 
> https://serverfault.com/questions/387935/whats-the-difference-betwen-the-single-dash-and-double-dash-flags-on-shell-comm
> 
> I have seen that many command line apps follow this convention

I changed my PR a while back to also cover that case. Good on that front.

**Comment by taori** [comment]
Since #62 fixed this i am wondering when you'll push master to release?

**Comment by bilal-fazlani** [comment]
I was doing some manual testing on **_mac_** and found some issues.

1. If you clone latest master
2. build solution
3. navigate to `CommandDotNet/CommandDotNet.Example/bin/Debug/netcoreapp2.1`
4. and run `dotnet CommandDotNet.Example.dll number --host "localhost" print`

it works fine, but if you run `dotnet CommandDotNet.Example.dll number --host "local host" print`
it return with an exception. 

If you go to SHA 5f37c4a8135910481d44fb6843af6654101b6d34 both the above commands works fine.

**Comment by bilal-fazlani** [comment]
I think this library 

1. automated tests to test these kind of issues
2. needs to be tested with a cli testing framework

**Comment by taori** [comment]
> 
> 
> I was doing some manual testing on **_mac_** and found some issues.
> 
>     1. If you clone latest master
> 
>     2. build solution
> 
>     3. navigate to `CommandDotNet/CommandDotNet.Example/bin/Debug/netcoreapp2.1`
> 
>     4. and run `dotnet CommandDotNet.Example.dll number --host "localhost" print`
> 
> 
> it works fine, but if you run `dotnet CommandDotNet.Example.dll number --host "local host" print`
> it return with an exception.
> 
> If you go to SHA [5f37c4a](https://github.com/bilal-fazlani/commanddotnet/commit/5f37c4a8135910481d44fb6843af6654101b6d34) both the above commands works fine.

what exception though? I'll try to reproduce it

**Comment by bilal-fazlani** [comment]
> what exception though? I'll try to reproduce it

```bash
dotnet CommandDotNet.Example.dll number --host "local host" print
Specify --help for a list of available options and commands.
Unrecognized command or argument 'host'

Usage: dotnet CommandDotNet.Example.dll number [options] [command]

Options:

  -h | --help
  Show help information

  --base-id      <TEXT>

  --host         <TEXT>    [localhost:8080]


Commands:

  print

Use "dotnet CommandDotNet.Example.dll number [command] --help" for more information about a command.

   at CommandDotNet.MicrosoftCommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName) in /Users/bilalmustafafazlani/RiderProjects/CommandDotNet/CommandDotNet/MicrosoftCommandLineUtils/CommandLineApplication.cs:line 416
   at CommandDotNet.MicrosoftCommandLineUtils.CommandLineApplication.Execute(String[] args) in /Users/bilalmustafafazlani/RiderProjects/CommandDotNet/CommandDotNet/MicrosoftCommandLineUtils/CommandLineApplication.cs:line 308
   at CommandDotNet.AppRunner`1.Run(String[] args) in /Users/bilalmustafafazlani/RiderProjects/CommandDotNet/CommandDotNet/AppRunner.cs:line 47
```

> Odd that it does not work on mac. Works fine on windows too

yeah, I think this needs multi os tests. travis supports that. will need to move it to travis.

**Comment by taori** [comment]
@bilal-fazlani line 416 points to a bracket instead of a code line. Could be a case of source not being updated?

**Comment by bilal-fazlani** [comment]
Let me double check that. 
Btw, I am in process of migrating to travis.com for CI to automate testing on mac, windows and linux. that should help us write test for this specific issue. 

Also, I think using https://github.com/simonmichael/shelltestrunner would be better to test this issue. I haven't tried it yet, it looks promising.

**Comment by taori** [comment]
Yeah i guess. Hopefully it was just an outdated master branch though. Would be rather odd if there was a mac only bug

**Comment by drewburlingame** [comment]
@bilal-fazlani @taori  I think there's a problem with this approach.  While creating the feature tests, I found [the following 2 scenarios](https://github.com/bilal-fazlani/commanddotnet/pull/111/files#diff-c9e003b56daf6195ef001dfc9bbd3301R33) where the argument is split when I don't think it should be.   

I don't think the rules are consistent across OS's for escaping strings and including spaces in arguments.  

Windows - dos prompt
![image](https://user-images.githubusercontent.com/103345/59160652-1adc8100-8ad0-11e9-94c6-2c05bb30be64.png)

Windows - git bash prompt
![image](https://user-images.githubusercontent.com/103345/59160664-3e073080-8ad0-11e9-9032-ad95b3a4c76b.png)

I don't think this framework should be responsible for trying to account for those.


I think the only time we should change what is passed into `string[] args` is when splitting options that contain `:` or `=` for value assignment.  Any other changes can violate the principle of least surprise.  We'd need to document them clearly.

**Comment by bilal-fazlani** [comment]
I agree. 
I would be happy if we free this lib from taking on this responsibility. 

As pointed by Drew it's behaviour can vary from one shell to to another.

**Comment by taori** [comment]
Perhaps it would be best to compile a list of how it should be parsing on each platform to produce the expected results then.

**Comment by drewburlingame** [comment]
In both examples above, I'm on the same machine.  There's not flag indicate which shell is running this.  This is a problem any application will have if it can be run across shells.  I think it will be the responsibility of the users to be aware of this.  Tool authors can help by including a `dump-args` command to review this and/or adding logging that can be used to troubleshoot.

I'm still working on filling out the feature tests.  Would either of you be willing to fix that branch :) ?

**Comment by bilal-fazlani** [comment]
I will sign up for this.

**Comment by drewburlingame** [comment]
@taori I missed your post before my last one and was about to type up the same thing.  It would be helpful to find or compile that list.   In addition to each platform, we'd need to include the shell's on that platform.  i.e. Windows would be dos, git bash, powershell.  Linux and Mac have bash, zsh and several others.  Is this something you'd be able to pull together?   

On a related note, how we determine what to display in the AppUsage is problematic.  Help defaults to assuming the app is running as a dotnet global command if a command name is provided via ApplicationMetadata.  The example includes `dotnet {command}`.  This isn't appropriate in many cases.  I updated it so that apps ending with .exe don't include this and I added a couple of options so devs could be more explicit.  I bring it up in case someone finds a way to be more deterministic with tihs while compiling the list for the different shells.

**Comment by taori** [comment]
@drewburlingame The whole reason i started using this lib was to have some sort of integrated argument parsing. If there was a way to have it behave the way ppl would expect it on each version that would be the ideal approach. unfortunately i have no idea how it should behave on mac/linus

**Comment by drewburlingame** [comment]
@taori I agree.  I'd like that too.  The challenge as I see them 

* Arguments are already parsed to some extent before being passed to our framework and I don't know how we can determine what rules were used in that parsing and what characters will have been removed.  
* We can't know which shell the app is being called from (not that I think we should need to).  
* Devs using a shell may know how that particular shell parses the values and if we change the behavior, we could be violating the principle of least surprise.  
* Given the number of shells and new shells being created, it will require additional maintenance for us to try to account for all the variations.

My personal preference is to provide tools to help devs troubleshoot when args don't parse the way they expect.  I also like the idea of a echo-args tool that will let devs get rapid feedback on how their app is parsed.    I've added a --echo-args option to some of my apps in the past that have been helpful.  It's like --help, but prints out the `string[] arg` and how the values were mapped into arguments.  I think it would be worthwhile to make this something that could be enabled.

**Comment by taori** [comment]
perhaps the best approach to solve this would be to have this controlled through parseroptions with something like a ICommandLineParser interface which splits the arguments. That way whenever someone experience issues he can just modify the behavior. Also that would allow to build in some shell detection possibly and replace the parsing behavior on demand.

**Comment by drewburlingame** [comment]
I'm still stuck on how could we determine what the shell didn't give us.   For example, what was the original string passed to 
![image](https://user-images.githubusercontent.com/103345/59160664-3e073080-8ad0-11e9-9032-ad95b3a4c76b.png)

This doesn't contain the quotes I used. Were they single or double quotes?

Since the shell is a different process, I don't see how we can replace the parsing behavior on demand.  The parsing is done before our process is spawned.  We could try to reconstruct the original string, but... we don't know what the shell removed so I don't think we can reliably reconstruct the string. 

Is there a .net feature that can tell us which shell was used?   The only way I can think of to determine the shell is to walk the parent processes tree.  This will require complex, OS-specific code.  That's a lot of complexity to introduce and maintain.

**Comment by taori** [comment]
it makes sense that the quotes are not parsed however. think of file names which might contain spaces - there has to be a way to pass that as argument. i can't imagine that it is impossible to get environmental info which might indicate how to parse arguments though. the sample you pointed out with different behavior depending on the shell is no doubt something which must be fixed.

**Comment by drewburlingame** [comment]
I'm not sure what there is for us to fix. As shown in [this PR](https://github.com/bilal-fazlani/commanddotnet/pull/126), the data is parsed before we can do anything with it and we don't have enough data to try to recover.  What you're asking for doesn't appear to be technically possible.

This problem has existed since... well probably since the second shell was created.   And each shell has a way to escape strings so args with spaces can be passed in.  You just have to learn the behavior of the shell you choose.  

I think this is a benefit instead of a problem.   If every program escaped strings differently, you'd have to learn how each program did it and each program would have to implement that logic.  Now, you only need to learn the behaviors of your chosen shell(s).  If you see the example on the PR, I know that double quotes will preserve spaces in both shells.  Single quotes only one.  So I use double quotes for both.   I just tested with Powershell and it has the same rules for double quotes but appears to have different rules for escaping double quotes.   I rarely use Powershell so I know I have to get up to speed on that.  I know that once I've learned the rules, they'll work the same for every program I use via Powershell.

**Comment by drewburlingame** [comment]
as a side note, I just learned that Powershell appears to be implemented similar to the echo-args command in [that PR](https://github.com/bilal-fazlani/commanddotnet/pull/126).  Each parsed arg is emitted in it's own line.  
![image](https://user-images.githubusercontent.com/103345/59294264-eb1cad00-8c78-11e9-8757-97645378765c.png)

**Comment by drewburlingame** [comment]
System.CommandLine has a `[parse]` directive for this.  Perhaps that's something we should consider. https://github.com/dotnet/command-line-api/wiki/Features-overview#parse-preview

**Comment by drewburlingame** [comment]
@taori after a coding frenzy the last couple of days, I've updated the parsing logic and introduced a way to keep standard parsing behavior but also enable custom transformations so you can achieve the behavior you're looking for.  See https://github.com/bilal-fazlani/commanddotnet/pull/142 for examples.  

If you `AppSettings.EnableDirectives` you can use the `[parse]` directive to debug your custom transformation in the console.

I've created release `2.8` which should be available on nuget shortly.

**Comment by drewburlingame** [comment]
@taori do you mind if we close this issue?

**Comment by taori** [comment]
@drewburlingame i don't mind at all if tests still run fine really. More bilal's decision though.

**Comment by bilal-fazlani** [comment]
👍  OK from my side . closing this.
