### ISSUE TITLE
Constructor Injection?

### ISSUE THREAD

**Issue by dotnetshadow** [bilal-fazlani/commanddotnet#70]
Hey there, 

Firstly it's been a great effort in producing such a great library, thank you

I was wondering if you have considered supporting constructor injection? (as opposed to only supporting property injection)? 

I do realise it complicate things on how you use constructors for options etc but I think it would be so beneficial going forward

Reading about property injection in general a lot of people often say to avoid it:
https://stackoverflow.com/questions/38459625/property-injection-in-asp-net-core

_"Please note that property injection is considered bad in 98% of all scenarios, because it hides dependencies and there is no guarantee that the object will be injected when the class is created.

With constructor injection you can enforce this via constructor and check for null and the not create the instance of the class. With property injection this is impossible and during unit tests its not obvious which services/dependencies the class requires when they are not defined in the constructor, so easy to miss and get NullReferenceExceptions.

This might also help with my other issue:
https://github.com/bilal-fazlani/commanddotnet/issues/42

Let me know your thoughts on this?

The only valid reason for Property Injection I ever found was to inject services into proxy classes generated by a third party library, i.e. WCF proxies created from an interface where you have no control about the object creation.

Avoid it everywhere else."_

**Comment by bilal-fazlani** [comment]
I agree. I never liked Property Injection either because of the same reasons as you mentioned. And as you pointed out, the only blocked in implementing constructor injection is global options. 

Just thinking, if we could swap these two..? So use properties for global options and constructor for dependency injection.. That would be nice I think..

**Comment by dotnetshadow** [comment]
Yes i would be in favour of this change. Especially when the default Microsoft DI system only supports constrictor injection

**Comment by bilal-fazlani** [comment]
I haven't started on this yet. Will make an attempt in next 2 weeks hopefully.

**Comment by dotnetshadow** [comment]
Awesome, appreciate your efforts

**Comment by drewburlingame** [comment]
Hi all.  I like the direction this is heading.  It would be great to be able to let a DI framework ctor the command objects even when there are global args defined.  I was thinking about the global args defined as Properties and I think there's one downside to that approach.  If there are multiple global args and they're used to configure the system, a class won't know when all of the properties have been provided.   Using a method to capture the global args allows us to perform logic with them.   The use case of #55 is a good example.  The ctor was able to then configure a proxy based on multiple parameters.  Instead of properties, what if a method could be decorated with a `GlobalAttribute`, similar to the `DefaultAttribute`?  I think this gives us the best of both worlds.  And since this would be a breaking change, this design will make it easier to fix existing ctors.  The devs simply convert the ctor to the decorated method.

**Comment by bilal-fazlani** [comment]
>If there are multiple global args and they're used to configure the system, a class won't know when all of the properties have been provided.

@drewburlingame With current impl, a constructor can only have options and not arguments. 
And when no value is provided to an option it falls back to its default value. Such as 0 for Int, false for Boolean etc. With this, we still wont know if all values are explicitly passed by user or not.

I am not completely sure of either approach. @drewburlingame would a pre command exec hook help the below use case?

>Using a method to capture the global args allows us to perform logic with them.

**Comment by drewburlingame** [comment]
> @drewburlingame With current impl, a constructor can only have options and not arguments.
And when no value is provided to an option it falls back to its default value. Such as 0 for Int, false for Boolean etc. With this, we still wont know if all values are explicitly passed by user or not.

I misspoke.  You can replace all 'global args' with 'global options'

> @drewburlingame would a pre command exec hook help the below use case?

Good question.  With #55, the pre-hook wasn't needed because the ctor served the same purpose.  With this change, the ctor would no longer work for that and a pre-hook would have value here.  That method could also be used to declare global options.


Since this would be a breaking change, you might want to toggle the feature with a feature flag in AppSettings and give people a version or two before removing the old feature.

**Comment by bilal-fazlani** [comment]
>With #55, the pre-hook wasn't needed because the ctor served the same purpose. With this change, the ctor would no longer work for that and a pre-hook would have value here. That method could also be used to declare global options.

I agree. Right now, none of the options seem "small changes"

Just thinking out loud now.. would it be sane (or even possible?) to use ctor for both global options and DI?

**Comment by drewburlingame** [comment]
Hmmm...  The ctor will be called either by this framework or a DI container.  How will this framework supply the global options to the ctor when called by the DI?  I think they'd always have to be part of an IArgumentModel and that IArgumentModel would have to be registered with the DI framework.   In this case, we'd need PR #56 and we'd need to extract the logic that ctor's the command so it can be replaced by the DI container.    We'd have to collect all of the global options before resolving the command from the container to ensure the IArgumentModel is populated when passed into the ctor.

I keep going back and forth on this.  Overall, I think it's a reasonable approach when using a DI container.  Using ctor-for-both vs a pre-hook method seem like trade-offs in complexity and principal of least surprise.  It would help to write up a document of the pros & cons of each approach.

**Comment by dotnetshadow** [comment]
Just want to say this is a great discussion, and it's an important lesson on how various changes can impact different use case scenarios. I think there are other commandline NuGet packages out there, perhaps it might worth taking a look on how they might of solved the issues?

**Comment by disklosr** [comment]
I too would be in favor of this change. Need to have a look at the code to get an understanding of the overall architecture and the changes needed to me made.

**Comment by drewburlingame** [comment]
I've been thinking about this more.  I've been working on a design to implement a middleware pipeline.  The signature would take a context object with an `Action next` delegate.   I think we should move away from the ctor options and replace it with a "middleware" method in the class.  If the method exists, options can be defined by additional parameters in the method.    We can look for the method with the context parameter.  Only one would be allowed per class.

**Comment by drewburlingame** [comment]
This is handled in the beta3/master branch.  You can see an example of the new command middleware method in the test here https://github.com/bilal-fazlani/commanddotnet/blob/beta-v3/master/CommandDotNet.Tests/FeatureTests/HostCommandMiddlewareOptions.cs#L245 

I removed support for ctor options and try to resolve command classes via DI before creating with Activator.

**Comment by dotnetshadow** [comment]
@drewburlingame Interesting, will have to look at this further. Would be good to see an example of the constructor injection and this together say with the calendar sample. Perhaps injecting a calendar service etc

**Comment by drewburlingame** [comment]
@dotnetshadow I hope to be working on the documentation next week.  In the meantime, here's a quick example.

```c#
public class Calendar
{
    private ICalenderService _calenderService;

    public Calendar(ICalenderService calenderService)
    {
        _calenderService = calenderService;
    }

    public void AddEvent(AddEventArgModel addEventArgs)
    {
        _calenderService.AddEvent(addEventArgs)
    }
}
```
and if in your example you previously used the ctor for ctor options, then the example would now look like 

```c#

public class Calendar
{
    private ICalenderService _calenderService;

    public Calendar(ICalenderService calenderService)
    {
        _calenderService = calenderService;
    }

    public Task<int> Init(CommandContext ctx, Func<CommandContext, Task<int>> next, string someOption)
    {
        _calendarService.SomeInit(someOption);
        return next(ctx);
    }

    public void AddEvent(AddEventArgModel addEventArgs)
    {
        _calenderService.AddEvent(addEventArgs)
    }
}
``` 

the `Init` method will be detected as a middleware method because of the `Func<CommandContext, Task<int>>` parameter.  It will be executed for every command defined in the class.  With this pattern, you can wrap call to `next` with any exception handling and cleanup.  As an alternative to the Init middleware method, you can create a middleware component that would perform this init for any class that takes an ICalenderService in the ctor.

**Comment by drewburlingame** [comment]
ctor injection is supported in 3.0.0
